backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "src/static/uploads" # this isn't actually used
public_folder: "/uploads" # neither is this

collections:
  - label: "homepage"
    name: homepage
    files:
      - label: "Decoy Links"
        name: Decoy Links
        file: "src/index.html"
        fields:
          - { label: Title, name: title, widget: string }
          - label: Links
            name: links
            widget: list
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Url, name: url, widget: string }
              - { label: Colour, name: color, widget: color }
